### ISSUE TITLE
Unable to parse response body into JSON

### ISSUE THREAD

**Issue by magnetas** [AfterShip/aftership-sdk-php#13]
Hi.

I started getting an error about the unparseable json response.

Both when registering new trackins (create) or retreiving details (get_by_id).

It seems that GET response cannot be treated as a JSON for some reason. Exception trace leads to /aftership/aftership-php-sdk/src/AfterShip/Core/Request.php line 56 ($response = $exception->getResponse()->json();) and then to the guzzle (/Guzzle/Http/Message/Response.php:861).

Any idea why is this happening?

What can be done to avoid the issue?

**Comment by marekyggdrasil** [comment]
Hello.

Could you please let us know which version of SDK are you using?

Reason I am asking is we recently updated AfterShip PHP SDK, now there is no Guzzle in our dependencies.

I will gladly provide some examples and help once I know more details. Meanwhile I encourage you to update and try the latest version based on Curl, probably the issue will occur no more.

Best regards. Keep us updated.

**Comment by magnetas** [comment]
Hello.

I believe we're using the 4.0.0 version. 

The problem doesn't happen all the time though.

**Comment by sunnychow** [comment]
Could you update to 5.0.5 version?

**Comment by sunnychow** [comment]
close it as it should work in after 5.0.5 version
