### ISSUE TITLE
Couriers::get() not compatibile with Request::GET()

### ISSUE THREAD

**Issue by xeandrej** [AfterShip/aftership-sdk-php#17]
Dear Aftershipers,

In your SDK i get the following ERROR:

  [Symfony\Component\Debug\Exception\ContextErrorException]                                                           
  Runtime Notice: Declaration of AfterShip\Couriers::get() should be compatible with AfterShip\Core\Request::GET($url, $headers, $body)

The error is solved when i add parameters in the extended courier class to get function:
public function get($url = null, $headers = null, $body = null)...

If i run your testing.php everything works fine. This is produced by symfony CLI.
Are you gonna commit this? I don't know what else to do.

Thanks,

**Comment by xeandrej** [comment]
Maybe it is best to change the name in the Request.php file from GET to HTTP_GET or something...

**Comment by sunnychow** [comment]
Thanks @xeandrej comments on this. 
We will handle it. Thanks.

**Comment by sunnychow** [comment]
we merge the code. it's fixed
