### ISSUE TITLE
Core Request and Errors

### ISSUE THREAD

**Issue by jminkler** [AfterShip/aftership-sdk-php#27]
`if ($code < 200 || $code >= 300) {
            $parsed = json_decode($response);
            $err_code = '';
            $err_message = '';
            $err_type = '';
            if (isset($parsed->meta->code)) {
                $err_code = $parsed->meta->code;
            }
            if (isset($parsed->meta->message)) {
                $err_message = $parsed->meta->message;
            }
            if (isset($parsed->meta->type)) {
                $err_type = $parsed->meta->type;
            }
            throw new AftershipException("$err_type: $err_code - $err_message");
        }`

Most likely will err with the message : -

**Comment by hans-lizihan** [comment]
i think this issue has been settle by #26
