### ISSUE TITLE
Update composer guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by CNSam** [AfterShip/aftership-sdk-php#30]
As per the composer message:

```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

**Comment by ArtemGordinsky** [comment]
I would gladly submit a PR, but I'm completely discouraged after seeing how #26 was never even acknowledged by the maintainers...

**Comment by hans-lizihan** [comment]
we internally no longer depend on guzzle, will remove the dependency entirely in the next release. Thanks for you patience.

**Comment by hans-lizihan** [comment]
https://packagist.org/packages/aftership/aftership-php-sdk#5.0.10 

published latest version on packagist
