### ISSUE TITLE
How to retrack shipment, which has tag "Expired"?

### ISSUE THREAD

**Issue by dariazaytseva** [AfterShip/aftership-sdk-php#38]
Hello! I try to retrack shipment, that has tag "Expired". I got an answer {"meta":{"code":200},"data":{...}}, but nothing changed in my system. I try to update that shipment, but again without success.
When I send GET-request to Aftership about that shipment, I get an answer with empty "checkpoints" parameter. But in Aftership tracking page there are a lot of checkpoints.

What should I do to update information in my system?

**Comment by hans-lizihan** [comment]
@dariazaytseva so sorry for very very late reply, completely leave this issue behind, have you got the solution?
