### ISSUE TITLE
create tracking with slugs in array

### ISSUE THREAD

**Issue by lambooni** [AfterShip/aftership-sdk-php#39]
I am having some issues submitting a list of potential slugs in an array format (submitting just a single one works fine).

using, 

`$trackings->create($tracknum, $params);`
and
`$params['slug'] =  array('dpd, 'dpd-uk');`

I am getting is a 4012 / Cannot detect courier. Activate courier at https://secure.aftership.com/settings/courier

I can submit a single tracker and it accepts it so I know the courier has been activated. Is the syntax wrong or am I using this incorrectly?

**Comment by hans-lizihan** [comment]
hi @lambooni, i have checked the code and i think the array of `slug` has been sent to api. could you please kindly send your username to my email (hans@aftership.com)? i will try to follow up~

**Comment by hans-lizihan** [comment]
closing this, it's an API issue that is being resolved, not the sdk issue.
