### ISSUE TITLE
API Problem - BadRequest: 400 - Schema validation error

### ISSUE THREAD

**Issue by paulboulevard** [AfterShip/aftership-sdk-php#51]
When I try to update a tracking by ID I get Schema validation error. I have tried it with various bit of data as described in the API documentation. I have even tried with just the id sent and empty data still the same response

I am using this method on the API

https://www.aftership.com/docs/aftership/477aefe813a65-update-a-tracking-by-id

I am currently testing the API.

``
 public function testUpdate()
    {
        $order = Order::query()->where('id', '=', 4)->with('shipping', 'tracking', 'lineItems')->first();

        $data = $this->getUpdatedTrackingData($order);

        /// $data = [];

        $id = $order->tracking->aftership_id;
        var_dump($id);

        try {
            $tracking = new Trackings(config('aftership.key'));
            $response = $tracking->updateById($order->tracking->aftership_id, $data);
        } catch (AfterShipException $e) {
            Sentry::captureException($e);
        }

        DD($response ?? $e, $data);
    }
```

  public function getUpdatedTrackingData($order): array
    {
        return [
            'id' => $order->tracking->aftership_id,
            'slug' => $this->getCourierSlug($order->tracking->provider),
            'tracking_number' => $order->tracking->number,

        ];
    }

**Comment by paulboulevard** [comment]
![Screenshot 2022-07-04 at 09 33 19](https://user-images.githubusercontent.com/102520597/177131919-7dd1b3bb-4309-4bab-a4f8-3b51d6ab1113.png)

**Comment by paulboulevard** [comment]
It seems that in creation of a tracking via the API the creation method is less stringent on the field for emails and smses

In this instance on creation of  a tracking the field for  email or sms does not care if it enclosed in an array []  eg:
'emails'                       => $order->customer_email,

When you are updating it via updateByID() method this is then required or you get schema validation error

 'emails'                       => [$order->customer_email],
 'smses'                       => [$order->customer->phone],

**Comment by paulboulevard** [comment]
Hi,

Thanks for the quick reply. I understand why ID is not updatable as it a
unique field to identify the tracking on aftership.
What happens in the instance of courier change and thus tracking number
change, is it not possible to update those fields, does the tracking have
to be deleted and a new tracking created?
We have instances where a parcel is assigned a courier and a tracking
number and then sometimes it is decided that this parcel is to be sent with
another courier and thus a new tracking number.

Regards

Paul ColleyPHP Developer  T. 0800 020 9910E. ***@***.***
BOULEVARDONLINE.CO.UK <https://boulevardonline.co.uk/>

**Comment by Bossa573** [comment]
for typical cases, the system is possible to provide checkpoints / tracking information even if the tracking number is updated on the courier side (e.g. multiple leg situation - that the package is being delivered by multiple couriers)
and you don't have to update the tracking number manually.
If you find that you cannot retrieve checkpoint information with the tracking number that you think it should be able to retrieve the information, you can also contact support@aftership.com for the investigation, thank you

**Comment by sunznx** [comment]
hello @paulboulevard 
We just fixed this case. Now you can update these fields now and will not get a schema validate error(if slug is same as tracking's slug)
