### ISSUE TITLE
No 2024-01 Support

### ISSUE THREAD

**Issue by olimortimer** [AfterShip/aftership-sdk-php#59]
Having seen the latest release of the 2024-01 API, including some new features, I reached out to AfterShip to ask when the SDK will support it...  I was told October 2025.  This seems a bit bizarre that you release a new API version, with new features, but you won't be updating your SDK to support them until 20+ months later.

https://www.aftership.com/docs/tracking/2024-01/quickstart/versioning

```
Our team is already working on it and will release the code of SDK with an updated API version with ETA October 2025.
```

**Comment by Bossa573** [comment]
Hello, sorry for the confusion. The new SDK release schedule for supporting versioned API is definitely NOT 2025-10. In fact our go, Java, and Ruby SDK are already supporting versioned API.

While we don't have a precise ETA at the moment, please expect the PHP SDK updates will be released within 4 weeks, thank you very much.
